<?php

use Illuminate\Database\Seeder;

class AttachmentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('attachments')->delete();
        
        \DB::table('attachments')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'mission-object.png',
                'alias' => 'MXuQvcP6lHxdEhPV.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-14 03:34:19',
                'updated_at' => '2020-03-14 03:34:19',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'our-story-image.jpg',
                'alias' => 'ybcxNYE6jnU4XtYX.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-14 04:01:10',
                'updated_at' => '2020-03-14 04:01:10',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'chapter-image.jpg',
                'alias' => 'VREfe6AN4t7e42up.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-14 07:38:19',
                'updated_at' => '2020-03-14 07:38:19',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'member-right-bg.png',
                'alias' => '8Vp5vg3d5pHs7Nnp.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-17 00:38:36',
                'updated_at' => '2020-03-17 00:38:36',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'partnership-img-bg.jpg',
                'alias' => 'FxJbNXJIrpmP5rNU.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-17 00:39:57',
                'updated_at' => '2020-03-17 00:39:57',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'member-right-bg.png',
                'alias' => 'zbxnqsiZOiU8Rsnt.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-17 01:07:17',
                'updated_at' => '2020-03-17 01:07:17',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'partnership-img-bg.jpg',
                'alias' => 'kuaftrKpAF9ebtZl.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-17 01:07:51',
                'updated_at' => '2020-03-17 01:07:51',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'grow-statline.png',
                'alias' => '5x3qCxPRQyhjPz7c.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-17 01:09:33',
                'updated_at' => '2020-03-17 01:09:33',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'logo1.png',
                'alias' => 'Gjir9hUX31ZmpUI7.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-17 01:34:21',
                'updated_at' => '2020-03-17 01:34:21',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'logo2.png',
                'alias' => 'imEpKhFNIPDwYGYo.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-17 01:34:23',
                'updated_at' => '2020-03-17 01:34:23',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'logo3.png',
                'alias' => 'wLkhR9szKVyHCL6N.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-17 01:34:25',
                'updated_at' => '2020-03-17 01:34:25',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'logo4.png',
                'alias' => 'SgLH6SjLJflAJskT.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-17 01:34:27',
                'updated_at' => '2020-03-17 01:34:27',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'logo5.png',
                'alias' => 'rzARLE2VuF9QFz3Z.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-17 01:34:29',
                'updated_at' => '2020-03-17 01:34:29',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'member-right-bg.png',
                'alias' => 'XORZzSMzUi5yx7OM.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-17 23:30:50',
                'updated_at' => '2020-03-17 23:30:50',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'partnership-img-bg.jpg',
                'alias' => 'rGc6qLPDtLs7fOIC.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-17 23:31:06',
                'updated_at' => '2020-03-17 23:31:06',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'grow-statline.png',
                'alias' => 'EiL9SKBGaGUYypkT.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-17 23:31:12',
                'updated_at' => '2020-03-17 23:31:12',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'member-right-bg.png',
                'alias' => 'pOs56sB1cEFQXRFT.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-18 00:31:38',
                'updated_at' => '2020-03-18 00:31:38',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'partnership-img-bg.jpg',
                'alias' => 'G17rJPMEtI8oY5d7.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-18 00:41:36',
                'updated_at' => '2020-03-18 00:41:36',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'partnership-img-bg.jpg',
                'alias' => 'X6DcSJGJOD4l94JH.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-18 00:45:44',
                'updated_at' => '2020-03-18 00:45:44',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'grow-statline.png',
                'alias' => '77eT6f66Le2YS7Gm.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-18 00:52:52',
                'updated_at' => '2020-03-18 00:52:52',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'logo1.png',
                'alias' => 'ct4phM6SyzVFZwAr.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-18 00:53:48',
                'updated_at' => '2020-03-18 00:53:48',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'logo2.png',
                'alias' => 'c0gATNO7o55VfGeQ.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-18 00:53:49',
                'updated_at' => '2020-03-18 00:53:49',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'logo3.png',
                'alias' => 'WspYZtbiHbamJ4Oy.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-18 00:53:51',
                'updated_at' => '2020-03-18 00:53:51',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'logo4.png',
                'alias' => 'AzUpbMK40qMgagNd.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-18 00:53:54',
                'updated_at' => '2020-03-18 00:53:54',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'logo5.png',
                'alias' => 'nLsD39S5XyE4Q77D.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-18 00:53:56',
                'updated_at' => '2020-03-18 00:53:56',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'logo5.png',
                'alias' => 'iKPgxZuZD0SjpaS5.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-18 00:53:59',
                'updated_at' => '2020-03-18 00:53:59',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'logo5.png',
                'alias' => 'DQlCf1dVqZu8NXe6.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-18 00:54:01',
                'updated_at' => '2020-03-18 00:54:01',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'logo1.png',
                'alias' => 'pAuR7Z1fLPromTrt.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-18 01:10:09',
                'updated_at' => '2020-03-18 01:10:09',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'logo1.png',
                'alias' => 'CBOg6jLvpYJ966b3.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-18 01:10:12',
                'updated_at' => '2020-03-18 01:10:12',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'mission-object.png',
                'alias' => 'ZdoJAe9fSvzmtnTV.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-18 01:21:47',
                'updated_at' => '2020-03-18 01:21:47',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'our-story-image.jpg',
                'alias' => 'HPZcSBljLtrfptCU.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-18 01:22:30',
                'updated_at' => '2020-03-18 01:22:30',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'chapter-image.jpg',
                'alias' => 'GX9lRCx2bo3x9NaP.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-18 01:35:23',
                'updated_at' => '2020-03-18 01:35:23',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'sponsor0.jpg',
                'alias' => 'YeNb5DU3Eddcqyjp.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-18 01:38:38',
                'updated_at' => '2020-03-18 01:38:38',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'sponsor1.jpg',
                'alias' => 'y6ghrl3YIizS4faT.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-18 01:41:08',
                'updated_at' => '2020-03-18 01:41:08',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'sponsor2.jpg',
                'alias' => 'VFJGoOLSqiAztmH7.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-18 01:41:11',
                'updated_at' => '2020-03-18 01:41:11',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'sponsor3.jpg',
                'alias' => 'dsAS9ZmopRzlfTix.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-18 01:41:14',
                'updated_at' => '2020-03-18 01:41:14',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'sponsor4.jpg',
                'alias' => 'A4BgWkQLD5IkEtK3.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-18 01:41:16',
                'updated_at' => '2020-03-18 01:41:16',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'sponsor5.jpg',
                'alias' => 'idhXpqnimP599V3c.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-18 01:41:19',
                'updated_at' => '2020-03-18 01:41:19',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'sponsor6.jpg',
                'alias' => 'dCzzSNUqmQXeSBO5.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-18 01:41:22',
                'updated_at' => '2020-03-18 01:41:22',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'sponsor7.jpg',
                'alias' => 'gB5uKBeJs0lKqioZ.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-18 01:41:24',
                'updated_at' => '2020-03-18 01:41:24',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'sponsor8.jpg',
                'alias' => 'BLg4ROJpLFZbcXWy.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-18 01:41:27',
                'updated_at' => '2020-03-18 01:41:27',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'sponsor9.jpg',
                'alias' => 'd4dKl1bVC2HCSgRb.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-18 01:41:30',
                'updated_at' => '2020-03-18 01:41:30',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'sponsor10.jpg',
                'alias' => 'dH9FBSomw3lu83AW.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-18 01:41:32',
                'updated_at' => '2020-03-18 01:41:32',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'sponsor11.jpg',
                'alias' => 'EjhqbHLvfMLVmfV9.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-18 01:41:35',
                'updated_at' => '2020-03-18 01:41:35',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'sponsor12.jpg',
                'alias' => 'hBtV3FcFxbzhm99q.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-18 01:41:38',
                'updated_at' => '2020-03-18 01:41:38',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'video-cover.jpg',
                'alias' => 'q4jgcfx5cHUlngtT.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-19 01:48:40',
                'updated_at' => '2020-03-19 01:48:40',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'AREAACentralNewJersey.mp4',
                'alias' => '42KYba5KGZ2Z9Ngc.mp4',
                'mime' => 'video/mp4',
                'folder' => 'Form',
                'extension' => 'mp4',
                'identifier' => 'default',
                'created_at' => '2020-03-19 01:49:22',
                'updated_at' => '2020-03-19 01:49:22',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'AREAACentralNewJersey.mp4',
                'alias' => 'epvrHkVZmDgJ0woB.mp4',
                'mime' => 'video/mp4',
                'folder' => 'Form',
                'extension' => 'mp4',
                'identifier' => 'default',
                'created_at' => '2020-03-19 01:50:57',
                'updated_at' => '2020-03-19 01:50:57',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'AREAACentralNewJersey.mp4',
                'alias' => 'GaBYCHMZy1FEv951.mp4',
                'mime' => 'video/mp4',
                'folder' => 'Form',
                'extension' => 'mp4',
                'identifier' => 'default',
                'created_at' => '2020-03-19 03:38:55',
                'updated_at' => '2020-03-19 03:38:55',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'AREAACentralNewJersey.mp4',
                'alias' => 'efMAMxJjnCSjimPK.mp4',
                'mime' => 'video/mp4',
                'folder' => 'Form',
                'extension' => 'mp4',
                'identifier' => 'default',
                'created_at' => '2020-03-19 03:39:01',
                'updated_at' => '2020-03-19 03:39:01',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'AREAACentralNewJersey.mp4',
                'alias' => 'LkhuOehzmY8ZrkCW.mp4',
                'mime' => 'video/mp4',
                'folder' => 'Form',
                'extension' => 'mp4',
                'identifier' => 'default',
                'created_at' => '2020-03-19 03:40:03',
                'updated_at' => '2020-03-19 03:40:03',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'AREAACentralNewJersey.mp4',
                'alias' => 'gDSiW3Sl2pH7arBe.mp4',
                'mime' => 'video/mp4',
                'folder' => 'Form',
                'extension' => 'mp4',
                'identifier' => 'default',
                'created_at' => '2020-03-19 03:43:52',
                'updated_at' => '2020-03-19 03:43:52',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'video-cover.jpg',
                'alias' => 'mTryauz7Pee50rVc.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-19 03:43:59',
                'updated_at' => '2020-03-19 03:43:59',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'partnership-img-bg.jpg',
                'alias' => '7TYkezb6x7NIudvj.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-19 03:44:01',
                'updated_at' => '2020-03-19 03:44:01',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'AREAACentralNewJersey.mp4',
                'alias' => '67UtWfrPKHwtijhP.mp4',
                'mime' => 'video/mp4',
                'folder' => 'Form',
                'extension' => 'mp4',
                'identifier' => 'default',
                'created_at' => '2020-03-19 03:44:05',
                'updated_at' => '2020-03-19 03:44:05',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'partnership-img-bg.jpg',
                'alias' => '0Zw3RrJPko67zXH6.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-19 03:45:53',
                'updated_at' => '2020-03-19 03:45:53',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'member-right-bg.png',
                'alias' => 'kbr5DcR8JcngckSU.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-03-19 03:46:01',
                'updated_at' => '2020-03-19 03:46:01',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'AREAACentralNewJersey.mp4',
                'alias' => 'UkMul8Apj9VuAoj9.mp4',
                'mime' => 'video/mp4',
                'folder' => 'Form',
                'extension' => 'mp4',
                'identifier' => 'default',
                'created_at' => '2020-03-19 03:46:03',
                'updated_at' => '2020-03-19 03:46:03',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'AREAACentralNewJersey.mp4',
                'alias' => '761pbDzrAL9W2ZDS.mp4',
                'mime' => 'video/mp4',
                'folder' => 'Form',
                'extension' => 'mp4',
                'identifier' => 'default',
                'created_at' => '2020-03-19 03:49:07',
                'updated_at' => '2020-03-19 03:49:07',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'video-cover.jpg',
                'alias' => 'XijqqUe62u8uLhC6.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-19 03:49:44',
                'updated_at' => '2020-03-19 03:49:44',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'AREAACentralNewJersey.mp4',
                'alias' => 'Y6BDQm3kZeU02nw2.mp4',
                'mime' => 'video/mp4',
                'folder' => 'Form',
                'extension' => 'mp4',
                'identifier' => 'default',
                'created_at' => '2020-03-19 03:49:53',
                'updated_at' => '2020-03-19 03:49:53',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'video-cover.jpg',
                'alias' => 'tpdLfIiIfrHeksWi.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-19 03:58:16',
                'updated_at' => '2020-03-19 03:58:16',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'AREAACentralNewJersey.mp4',
                'alias' => 'vDMijFBc0F5WICNX.mp4',
                'mime' => 'video/mp4',
                'folder' => 'Form',
                'extension' => 'mp4',
                'identifier' => 'default',
                'created_at' => '2020-03-19 03:58:18',
                'updated_at' => '2020-03-19 03:58:18',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'video-cover.jpg',
                'alias' => 'FHeWQkphie61FC3t.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-19 03:58:31',
                'updated_at' => '2020-03-19 03:58:31',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'chapter-image.jpg',
                'alias' => 'JIXsAbUp8Eok2OMB.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Form',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-19 03:58:37',
                'updated_at' => '2020-03-19 03:58:37',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'AREAACentralNewJersey.mp4',
                'alias' => 'KN8TOlC7Y62UwU9H.mp4',
                'mime' => 'video/mp4',
                'folder' => 'Form',
                'extension' => 'mp4',
                'identifier' => 'default',
                'created_at' => '2020-03-19 03:58:43',
                'updated_at' => '2020-03-19 03:58:43',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'AREAACentralNewJersey.mp4',
                'alias' => 'q1ZqlonyJvk5xRqL.mp4',
                'mime' => 'video/mp4',
                'folder' => 'Form',
                'extension' => 'mp4',
                'identifier' => 'default',
                'created_at' => '2020-03-19 03:58:57',
                'updated_at' => '2020-03-19 03:58:57',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'name' => '',
                'alias' => '4v55kxlplprW4ylh.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'BoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-20 03:21:32',
                'updated_at' => '2020-03-20 03:21:32',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'name' => '',
                'alias' => 'gKwrSdiTsOgOnfub.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'BoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-20 03:24:12',
                'updated_at' => '2020-03-20 03:24:12',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'name' => '',
                'alias' => 'pn4Vg55rgOZxTb3W.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'BoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-20 03:24:56',
                'updated_at' => '2020-03-20 03:24:56',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'name' => '',
                'alias' => 'CJGWrA8HoQ2UZoFe.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'BoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-20 03:25:36',
                'updated_at' => '2020-03-20 03:25:36',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'name' => '',
                'alias' => 'Jg28O7dCBLg1CUlG.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'BoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-20 03:26:16',
                'updated_at' => '2020-03-20 03:26:16',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'name' => '',
                'alias' => 'J8qmopY0AZ37auAI.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'BoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-20 03:26:59',
                'updated_at' => '2020-03-20 03:26:59',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'name' => '',
                'alias' => 'zlTsFfLa4SKYhvl2.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'BoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-20 03:27:45',
                'updated_at' => '2020-03-20 03:27:45',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'name' => '',
                'alias' => 'WCogUzMBvtlgDxIC.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'BoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-20 03:28:23',
                'updated_at' => '2020-03-20 03:28:23',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'name' => '',
                'alias' => 'pTiFAyn73iE7L4Jr.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'BoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-20 03:29:15',
                'updated_at' => '2020-03-20 03:29:15',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'name' => '',
                'alias' => 'qhG6yzoEVN18Wowt.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'BoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-20 03:30:22',
                'updated_at' => '2020-03-20 03:30:22',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'name' => '',
                'alias' => 'G0hm6CP9t2tMdr7H.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Event',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-21 04:25:06',
                'updated_at' => '2020-03-25 23:46:15',
                'deleted_at' => '2020-03-25 23:46:15',
            ),
            78 => 
            array (
                'id' => 79,
                'name' => '',
                'alias' => 'XzXoztzStodgFvOJ.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Event',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-03-25 23:46:15',
                'updated_at' => '2020-03-25 23:46:15',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'name' => '',
                'alias' => '7mo9oaoMSZUYvwHq.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'ChapterHome',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-04-07 00:43:11',
                'updated_at' => '2020-04-07 00:43:11',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'name' => '',
                'alias' => 'RTeMFUO23kSED799.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Event',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-04-07 23:57:17',
                'updated_at' => '2020-04-07 23:57:17',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'name' => '',
                'alias' => 'rwTMbzVXmbLNP35w.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'ChapterEvent',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-04-07 23:58:40',
                'updated_at' => '2020-04-08 00:37:23',
                'deleted_at' => '2020-04-08 00:37:23',
            ),
            82 => 
            array (
                'id' => 83,
                'name' => '',
                'alias' => '2Gxg3Iser6NLa6KY.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'ChapterEvent',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-04-08 00:23:08',
                'updated_at' => '2020-04-08 00:23:08',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'name' => '',
                'alias' => 'uMnpb1FnG5ptCB2h.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'ChapterEvent',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-04-08 00:37:23',
                'updated_at' => '2020-04-18 06:50:07',
                'deleted_at' => '2020-04-18 06:50:07',
            ),
            84 => 
            array (
                'id' => 85,
                'name' => '',
                'alias' => 'fnD9zW4B9FpzSvq1.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'ChapterEvent',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-04-08 00:38:11',
                'updated_at' => '2020-04-18 06:49:54',
                'deleted_at' => '2020-04-18 06:49:54',
            ),
            85 => 
            array (
                'id' => 86,
                'name' => '',
                'alias' => 'AXim1uykHkZxClVN.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'ChapterBoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-04-08 02:23:48',
                'updated_at' => '2020-04-08 02:23:48',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'name' => '',
                'alias' => 'ZCkhgitN3FFQX4FI.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'ChapterEvent',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-04-18 06:49:54',
                'updated_at' => '2020-04-18 06:49:54',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'name' => '',
                'alias' => 'Njj1qpiDJNeDxeIE.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'ChapterEvent',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-04-18 06:50:07',
                'updated_at' => '2020-04-18 06:50:07',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'name' => '',
                'alias' => 'Fc7vsh9bRDSECavG.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'ChapterBoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-04-22 00:01:22',
                'updated_at' => '2020-04-22 00:01:22',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'name' => '',
                'alias' => 'ygqdFsxeC5f7IaHl.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'ChapterBoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-04-22 00:06:44',
                'updated_at' => '2020-04-22 00:06:44',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'name' => '',
                'alias' => 'DL5kLtlaZHvzVy8I.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'ChapterBoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-04-22 00:07:01',
                'updated_at' => '2020-04-22 00:07:01',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'name' => '',
                'alias' => 'vcCdnTrGqWlWcjBK.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'ChapterBoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-04-22 00:07:19',
                'updated_at' => '2020-04-22 00:07:19',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'name' => '',
                'alias' => 'Jm9VjgQbt6Tx5iTz.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'ChapterBoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-04-22 00:07:33',
                'updated_at' => '2020-04-22 00:07:33',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'name' => '',
                'alias' => 'krcHTkaN2ediJsgA.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'ChapterBoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-04-22 00:07:49',
                'updated_at' => '2020-04-22 00:07:49',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'name' => '',
                'alias' => '6b1FTg2hQOFJUZwG.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'ChapterBoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-04-22 00:07:58',
                'updated_at' => '2020-04-22 00:07:58',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'name' => '',
                'alias' => '77vDJKkTSc7lybtl.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'ChapterBoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-04-22 00:08:12',
                'updated_at' => '2020-04-22 00:08:12',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'name' => '',
                'alias' => 'gJXdcTYQy0Yy2yN6.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'ChapterBoardMember',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-04-22 00:08:36',
                'updated_at' => '2020-04-22 00:08:36',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'name' => 'testimonial-image.png',
                'alias' => 'mqWSy7LOm0wddpt4.png',
                'mime' => 'image/png',
                'folder' => 'Form',
                'extension' => 'png',
                'identifier' => 'default',
                'created_at' => '2020-05-30 02:51:32',
                'updated_at' => '2020-05-30 02:51:32',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'name' => '',
                'alias' => '1LmEtpnASrRdc4Ay.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Page',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-05-30 03:20:02',
                'updated_at' => '2020-05-30 03:20:02',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'name' => '',
                'alias' => 'X8wCu46CflqmMwdk.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Page',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-05-30 03:37:44',
                'updated_at' => '2020-05-30 03:37:44',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'name' => '',
                'alias' => 'HGkgYZK0WAm6aooQ.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Page',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-05-30 03:39:34',
                'updated_at' => '2020-05-30 03:39:34',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'name' => '',
                'alias' => '9Ve05THJ4IHA2aiW.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Page',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-05-30 03:41:02',
                'updated_at' => '2020-05-30 03:41:02',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'name' => '',
                'alias' => 'wpTJwLn9cgBBnxVx.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Page',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-05-30 03:52:31',
                'updated_at' => '2020-05-30 03:52:31',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'name' => '',
                'alias' => 'iWsatIm3UShUonOy.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Page',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-05-30 03:55:14',
                'updated_at' => '2020-05-30 03:55:14',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'name' => '',
                'alias' => 'tUIjusnt1t84gnKD.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Page',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-05-30 03:58:55',
                'updated_at' => '2020-05-30 03:58:55',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'name' => '',
                'alias' => 'tboKImOf7c8V0rMx.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Page',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-05-30 04:01:01',
                'updated_at' => '2020-05-30 04:01:01',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'name' => '',
                'alias' => 'XLgoRnpVWm07Qd1C.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Page',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-05-30 04:02:27',
                'updated_at' => '2020-05-30 04:02:27',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'name' => '',
                'alias' => 'VF1CxFHXdIWgso5v.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Page',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-05-30 04:03:45',
                'updated_at' => '2020-05-30 04:03:45',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'name' => '',
                'alias' => 'ChC39MRsKYEljRaP.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Page',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-05-30 04:05:25',
                'updated_at' => '2020-05-30 04:05:25',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'name' => '',
                'alias' => 'fXIVwaaBr48jcHEw.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Page',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-05-30 04:06:59',
                'updated_at' => '2020-05-30 04:06:59',
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'name' => '',
                'alias' => '73gEoSQ0uLYdz5si.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Page',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-05-30 04:09:02',
                'updated_at' => '2020-05-30 04:09:02',
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'name' => '',
                'alias' => 'YNtcxEpPtBgKO3YY.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Page',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-05-30 04:10:32',
                'updated_at' => '2020-05-30 04:10:32',
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'name' => '',
                'alias' => 'xAgwtCe3BP3LKdPE.jpg',
                'mime' => 'image/jpeg',
                'folder' => 'Page',
                'extension' => 'jpg',
                'identifier' => 'default',
                'created_at' => '2020-05-30 04:11:41',
                'updated_at' => '2020-05-30 04:11:41',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}