<?php

use Illuminate\Database\Seeder;

class ChapterBoardMembersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('chapter_board_members')->delete();
        
        \DB::table('chapter_board_members')->insert(array (
            0 => 
            array (
                'id' => 1,
                'chapter_id' => 1,
                'first_name' => 'Ronda',
                'last_name' => 'Ching-Day',
                'avatar' => 'C:\\wamp64\\tmp\\php3877.tmp',
                'position' => 'President',
                'bio' => '',
                'order' => 1,
                'is_active' => 1,
                'type' => 1,
                'slug' => 'ronda-ching-day',
                'created_at' => '2020-04-08 02:01:09',
                'updated_at' => '2020-04-27 09:13:03',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'chapter_id' => 1,
                'first_name' => 'Thomas',
                'last_name' => 'Tay',
                'avatar' => NULL,
                'position' => 'Vice President',
                'bio' => '',
                'order' => 2,
                'is_active' => 1,
                'type' => 1,
                'slug' => 'thomas-tay',
                'created_at' => '2020-04-21 07:03:07',
                'updated_at' => '2020-04-21 07:03:07',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'chapter_id' => 1,
                'first_name' => 'Abe',
                'last_name' => 'Lee',
                'avatar' => 'C:\\wamp64\\tmp\\phpC433.tmp',
                'position' => 'Secretary',
                'bio' => '',
                'order' => 3,
                'is_active' => 1,
                'type' => 1,
                'slug' => 'abe-lee',
                'created_at' => '2020-04-21 07:05:52',
                'updated_at' => '2020-04-22 00:01:39',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'chapter_id' => 1,
                'first_name' => 'Sharon',
                'last_name' => 'Rasos',
                'avatar' => NULL,
                'position' => 'Treasurer',
                'bio' => '',
                'order' => 4,
                'is_active' => 1,
                'type' => 1,
                'slug' => 'sharon-rasos',
                'created_at' => '2020-04-21 07:06:42',
                'updated_at' => '2020-04-21 07:06:42',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'chapter_id' => 1,
                'first_name' => 'Claire',
                'last_name' => 'Doi',
                'avatar' => 'C:\\wamp64\\tmp\\phpAEA0.tmp',
                'position' => '',
                'bio' => '',
                'order' => 5,
                'is_active' => 1,
                'type' => 2,
                'slug' => 'claire-doi',
                'created_at' => '2020-04-21 22:16:18',
                'updated_at' => '2020-04-22 00:06:44',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'chapter_id' => 1,
                'first_name' => 'Christine',
                'last_name' => 'Kim',
                'avatar' => 'C:\\wamp64\\tmp\\phpF280.tmp',
                'position' => '',
                'bio' => '',
                'order' => 6,
                'is_active' => 1,
                'type' => 2,
                'slug' => 'christine-kim',
                'created_at' => '2020-04-21 22:16:42',
                'updated_at' => '2020-04-22 00:07:01',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'chapter_id' => 1,
                'first_name' => 'Gina',
                'last_name' => 'Duncan',
                'avatar' => 'C:\\wamp64\\tmp\\php369F.tmp',
                'position' => '',
                'bio' => '',
                'order' => 7,
                'is_active' => 1,
                'type' => 2,
                'slug' => 'gina-duncan',
                'created_at' => '2020-04-21 22:16:57',
                'updated_at' => '2020-04-22 00:07:19',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'chapter_id' => 1,
                'first_name' => 'Lisa',
                'last_name' => 'Van Den Heuval',
                'avatar' => 'C:\\wamp64\\tmp\\php6ED6.tmp',
                'position' => 'Publicity Chairperson',
                'bio' => '',
                'order' => 8,
                'is_active' => 1,
                'type' => 2,
                'slug' => 'lisa-van-den-heuval',
                'created_at' => '2020-04-21 22:17:20',
                'updated_at' => '2020-04-22 00:07:33',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'chapter_id' => 1,
                'first_name' => 'Judy',
                'last_name' => 'Sykes',
                'avatar' => 'C:\\wamp64\\tmp\\phpADE4.tmp',
                'position' => '',
                'bio' => '',
                'order' => 9,
                'is_active' => 1,
                'type' => 2,
                'slug' => 'judy-sykes',
                'created_at' => '2020-04-21 22:17:39',
                'updated_at' => '2020-04-22 00:07:49',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'chapter_id' => 1,
                'first_name' => 'Bruce',
                'last_name' => 'McDonald',
                'avatar' => 'C:\\wamp64\\tmp\\phpCF96.tmp',
                'position' => '',
                'bio' => '',
                'order' => 10,
                'is_active' => 1,
                'type' => 2,
                'slug' => 'bruce-mcdonald',
                'created_at' => '2020-04-21 22:17:57',
                'updated_at' => '2020-04-22 00:07:58',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'chapter_id' => 1,
                'first_name' => 'Mami',
                'last_name' => 'Takeda',
                'avatar' => 'C:\\wamp64\\tmp\\php6D4.tmp',
                'position' => '',
                'bio' => '',
                'order' => 11,
                'is_active' => 1,
                'type' => 2,
                'slug' => 'mami-takeda',
                'created_at' => '2020-04-21 22:18:17',
                'updated_at' => '2020-04-22 00:08:12',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'chapter_id' => 1,
                'first_name' => 'Christina',
                'last_name' => 'Berry',
                'avatar' => 'C:\\wamp64\\tmp\\php636C.tmp',
                'position' => '',
                'bio' => '',
                'order' => 12,
                'is_active' => 1,
                'type' => 2,
                'slug' => 'christina-berry',
                'created_at' => '2020-04-21 22:18:33',
                'updated_at' => '2020-04-22 00:08:36',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'chapter_id' => 1,
                'first_name' => 'Rachel-Joy',
                'last_name' => 'Nisperos',
                'avatar' => NULL,
                'position' => '',
                'bio' => '',
                'order' => 13,
                'is_active' => 1,
                'type' => 2,
                'slug' => 'rachel-joy-nisperos',
                'created_at' => '2020-04-21 22:18:49',
                'updated_at' => '2020-04-21 22:18:49',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'chapter_id' => 1,
                'first_name' => 'Rommel',
                'last_name' => 'Guzman',
                'avatar' => NULL,
                'position' => '',
                'bio' => '',
                'order' => 14,
                'is_active' => 1,
                'type' => 2,
                'slug' => 'rommel-guzman',
                'created_at' => '2020-04-21 22:19:02',
                'updated_at' => '2020-04-21 22:19:02',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'chapter_id' => 1,
                'first_name' => 'Earl',
                'last_name' => 'Lee',
                'avatar' => NULL,
                'position' => '',
                'bio' => '',
                'order' => 15,
                'is_active' => 1,
                'type' => 3,
                'slug' => 'earl-lee',
                'created_at' => '2020-04-21 22:26:21',
                'updated_at' => '2020-04-21 22:26:21',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'chapter_id' => 1,
                'first_name' => 'Patti',
                'last_name' => 'Nakagawa',
                'avatar' => NULL,
                'position' => '',
                'bio' => '',
                'order' => 16,
                'is_active' => 1,
                'type' => 3,
                'slug' => 'patti-nakagawa',
                'created_at' => '2020-04-21 22:26:33',
                'updated_at' => '2020-04-21 22:26:33',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'chapter_id' => 1,
                'first_name' => 'Kalama',
                'last_name' => 'Kim',
                'avatar' => NULL,
                'position' => '',
                'bio' => '',
                'order' => 17,
                'is_active' => 1,
                'type' => 3,
                'slug' => 'kalama-kim',
                'created_at' => '2020-04-21 22:26:55',
                'updated_at' => '2020-04-21 22:26:55',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'chapter_id' => 1,
                'first_name' => 'James',
                'last_name' => 'Wright',
                'avatar' => NULL,
                'position' => '',
                'bio' => '',
                'order' => 18,
                'is_active' => 1,
                'type' => 3,
                'slug' => 'james-wright',
                'created_at' => '2020-04-21 22:27:10',
                'updated_at' => '2020-04-21 22:27:10',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}