<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'status' => 0,
                'email' => 'super_admin@dogandrooster.com',
                'user_name' => 'super_admin',
                'password' => '$2y$10$fvcK8QNeRUpnZF3HhyE7DOS5luEhVKAcRgIoJlWidiKAHyneYgeHi',
                'first_name' => 'Super',
                'middle_name' => '',
                'last_name' => 'Admin',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => NULL,
                'is_active' => 1,
                'last_login' => '2020-05-30 00:39:18',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2018-03-01 21:14:04',
                'updated_at' => '2020-05-30 00:39:18',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'status' => 0,
                'email' => 'test1@dogandrooster.net',
                'user_name' => 'webmaster',
                'password' => '$2y$10$O04W12OFlU2ieWp.dA268e6B44PuMKIy2G6wUDs9fWb8ptqc1ZQWi',
                'first_name' => 'Webmaster',
                'middle_name' => '',
                'last_name' => 'Webmaster',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => NULL,
                'is_active' => 1,
                'last_login' => '2020-05-30 05:09:50',
                'token' => NULL,
                'remember_token' => 'W4duZVHX8YxFdvwv8OGZpGTKI1AqrfcoZOnzDLBjgvH0rI8zaMPeC74ovlZV',
                'created_at' => '2018-03-01 21:14:04',
                'updated_at' => '2020-05-30 05:09:50',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'status' => 0,
                'email' => 'customer_user@dogandrooster.com',
                'user_name' => 'customer_user',
                'password' => '$2y$10$kcApan9j3RxaYDYYtCZC8O7RqI/979pAHy2H2T1fwNYC8yzCsE0Ui',
                'first_name' => 'Customer',
                'middle_name' => '',
                'last_name' => 'One',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => NULL,
                'is_active' => 1,
                'last_login' => '2020-05-29 21:58:04',
                'token' => NULL,
                'remember_token' => 'RSVxvemp6HnRLVwFgbCg46teg8rWqWpIiQYyrAoBbu1oO2uusSvKdDnC5d6d',
                'created_at' => '2018-03-01 21:14:05',
                'updated_at' => '2020-05-29 21:58:04',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'status' => 0,
                'email' => 'admin_aloha@email.com',
                'user_name' => 'admin_aloha',
                'password' => '$2y$10$xbn6YK0ruU7tQ93B6yok5OtX6ZOnwdy8CIKQk0AbYCcLaSO5.E03m',
                'first_name' => 'Chapter',
                'middle_name' => '',
                'last_name' => 'Admin',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 1,
                'is_active' => 1,
                'last_login' => '2020-05-30 01:20:33',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-04-07 07:25:20',
                'updated_at' => '2020-05-30 01:20:33',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 14,
                'status' => 0,
                'email' => 'customer1@email.com',
                'user_name' => 'customer_1',
                'password' => '$2y$10$S5EMCRLwUDq8Okb.AsnU5epF2rCnHusZP6g6ADjsMmVPUJ58MQOsu',
                'first_name' => 'Mami',
                'middle_name' => '',
                'last_name' => 'Takeda',
                'phone' => '123 456 789',
                'profile_image' => 'public/storage/ChapterBoardMember/77vDJKkTSc7lybtl.jpg',
                'chapter_id' => 1,
                'is_active' => 1,
                'last_login' => '2020-05-30 01:32:22',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-04-22 22:10:27',
                'updated_at' => '2020-05-30 01:32:22',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 15,
                'status' => 0,
                'email' => 'customer2@email.com',
                'user_name' => 'customer_2',
                'password' => '$2y$10$3FbU/JFaHaTr5KwP0fRaQegIvLz3zd8G6AXaBTZ4OLJujWVyBlY0O',
                'first_name' => 'Bruce',
                'middle_name' => '',
                'last_name' => 'McDonald',
                'phone' => '8888',
                'profile_image' => 'public/storage/ChapterBoardMember/6b1FTg2hQOFJUZwG.jpg',
                'chapter_id' => 1,
                'is_active' => 1,
                'last_login' => '2020-05-16 07:55:40',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-04-22 22:11:49',
                'updated_at' => '2020-05-16 07:55:51',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 16,
                'status' => 0,
                'email' => 'customer3@email.com',
                'user_name' => 'customer_3',
                'password' => '$2y$10$8M.HceoGlu753fAZccGri.VsIGVql.J9WrJ/YUzt249vRwK8ECJA6',
                'first_name' => 'Patrisha',
                'middle_name' => '',
                'last_name' => 'Kingsley',
                'phone' => '0',
                'profile_image' => 'public/images/member-detail.jpg',
                'chapter_id' => 2,
                'is_active' => 1,
                'last_login' => '2020-04-23 13:13:23',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-04-22 22:13:23',
                'updated_at' => '2020-04-22 22:13:23',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 17,
                'status' => 0,
                'email' => 'customer4@email.com',
                'user_name' => 'customer_4',
                'password' => '$2y$10$yvG14nSJXwXBD8FZIXvEKemek7n0tWRXI4PkiDlbWzn8MiAS/HsXG',
                'first_name' => 'Stephen',
                'middle_name' => '',
                'last_name' => 'Chow',
                'phone' => '0',
                'profile_image' => 'public/storage/BoardMember/WCogUzMBvtlgDxIC.jpg',
                'chapter_id' => 1,
                'is_active' => 1,
                'last_login' => '2020-04-23 13:14:14',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-04-22 22:14:14',
                'updated_at' => '2020-04-22 22:14:14',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 18,
                'status' => 0,
                'email' => 'johndoe@email.com',
                'user_name' => 'customer5',
                'password' => '$2y$10$oJsLTB3EdRq1VdkyVV7ryulnoT0SBp7yYjH0Y0KJcitXpNxBeCojW',
                'first_name' => 'John',
                'middle_name' => '',
                'last_name' => 'Doe',
                'phone' => '1234567890',
                'profile_image' => '',
                'chapter_id' => 1,
                'is_active' => 1,
                'last_login' => '2020-04-30 23:58:19',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-04-30 08:58:19',
                'updated_at' => '2020-04-30 08:58:19',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 19,
                'status' => 0,
                'email' => 'carolynn@dogandrooster.com',
                'user_name' => 'carolynnDNR',
                'password' => '$2y$10$MiLhTQ.4aP7Q2L4wAmFqE.vCIG0E4mmqsOX2qO2tPo51qn8CkOkue',
                'first_name' => 'Carolynn',
                'middle_name' => '',
                'last_name' => 'Edmonson',
                'phone' => '123-456-7890',
                'profile_image' => 'public/uploads/profile_image/Business-Headshot-Women-006-1589328058.jpg',
                'chapter_id' => 1,
                'is_active' => 1,
                'last_login' => '2020-05-28 21:22:29',
                'token' => NULL,
                'remember_token' => '85MuGOrXyQENAvUi1smyDGToeclXiSUT72B7HCNGWkCRymkqXbGvDf0mLJii',
                'created_at' => '2020-05-01 00:29:20',
                'updated_at' => '2020-05-28 21:22:29',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 20,
                'status' => 0,
                'email' => 'johnnydoe@email.com',
                'user_name' => 'customer10',
                'password' => '$2y$10$MkkdLO9RtSnNZOdcInPjZ.rDstYHtrkrnQgrmkeTifNIQDmyYMTKS',
                'first_name' => 'Johnny',
                'middle_name' => '',
                'last_name' => 'Doe',
                'phone' => '8888',
                'profile_image' => '',
                'chapter_id' => 2,
                'is_active' => 1,
                'last_login' => '2020-05-11 20:46:27',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-05 01:41:53',
                'updated_at' => '2020-05-11 20:46:27',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 21,
                'status' => 0,
                'email' => 'jmiranda@areaa.org',
                'user_name' => 'jazz@areaa',
                'password' => '$2y$10$b6uTaXgjih9ziAlSJcXHqu2zKzI9rd2zpZTw5q68TTveNoVgQM0bO',
                'first_name' => 'Jazz',
                'middle_name' => '',
                'last_name' => 'Miranda',
                'phone' => '',
                'profile_image' => 'public/uploads/profile_image/BA9DC662-7098-4B73-9ABE-DAE77C-1589900236.jpeg',
                'chapter_id' => 0,
                'is_active' => 1,
                'last_login' => '2020-05-29 21:26:55',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-19 15:54:54',
                'updated_at' => '2020-05-29 21:26:55',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 22,
                'status' => 0,
                'email' => 'vshields@areaa.org',
                'user_name' => 'Vanessa Shields',
                'password' => '$2y$10$BilxMUKftuE/cT0p956fkeyu2k.QTwUL7EeYelPbf4QkpHXhaQoOC',
                'first_name' => 'Vanessa',
                'middle_name' => '',
                'last_name' => 'Shields',
                'phone' => '6199552619',
                'profile_image' => '',
                'chapter_id' => 1,
                'is_active' => 1,
                'last_login' => '2020-05-20 01:42:25',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-19 18:42:25',
                'updated_at' => '2020-05-19 18:42:25',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 23,
                'status' => 0,
                'email' => 'admin@areaa.org',
                'user_name' => 'admin',
                'password' => '$2y$10$eWV4BfLoc8plQZ78LXn.ZO1WGjhsuz7VEh3AJrCAV49OlMnGcF1Ly',
                'first_name' => 'AREAA',
                'middle_name' => '',
                'last_name' => 'Admin',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => NULL,
                'is_active' => 1,
                'last_login' => '2020-05-21 04:31:55',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-21 00:10:33',
                'updated_at' => '2020-05-21 04:31:55',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 24,
                'status' => 0,
                'email' => 'admin_austin@email.com',
                'user_name' => 'admin_austin',
                'password' => '$2y$10$RKDdGcyVxykzw5z2CUL/Y.NB4hTzc.ER12m8RkueYwV/cOzGvL/Xq',
                'first_name' => 'Austin',
                'middle_name' => '',
                'last_name' => 'Austin',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 3,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:06:01',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:06:01',
                'updated_at' => '2020-05-28 22:06:01',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 25,
                'status' => 0,
                'email' => 'admin_boston@email.com',
                'user_name' => 'admin_boston',
                'password' => '$2y$10$4r.UUtp8V4vi.FoqvQVI/uzn734clC6OkkVGBixDUSs5xWsMOuWwO',
                'first_name' => 'Boston',
                'middle_name' => '',
                'last_name' => 'Boston',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 4,
                'is_active' => 1,
                'last_login' => '2020-05-30 02:07:32',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:06:32',
                'updated_at' => '2020-05-30 02:07:32',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 26,
                'status' => 0,
                'email' => 'admin_brooklyn@email.com',
                'user_name' => 'admin_brooklyn',
                'password' => '$2y$10$SHxf23EFs91gQiy62D9DWOEdHy3mF2Y1l1BQEugq74PcJFGN6QORi',
                'first_name' => 'Brooklyn',
                'middle_name' => '',
                'last_name' => 'Brooklyn',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 5,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:07:20',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:07:20',
                'updated_at' => '2020-05-28 22:07:20',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 27,
                'status' => 0,
                'email' => 'admin_caorangecounty@email.com',
                'user_name' => 'admin_caorangecounty',
                'password' => '$2y$10$bEk0lkBFf70uUhzRKFEZ1.dEy30IwkESO95PgOhz8GdaAuY2P5D7e',
                'first_name' => 'CA Orange County',
                'middle_name' => '',
                'last_name' => 'CA Orange County',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 6,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:07:51',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:07:51',
                'updated_at' => '2020-05-28 22:07:51',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 28,
                'status' => 0,
                'email' => 'admin_central_new_jersey@email.com',
                'user_name' => 'admin_central_new_jersey',
                'password' => '$2y$10$sgJHSSXtuAlfNckcTzRTru6ui5pZWCjWRYP8yhUVgVtHYTg0B/Hla',
                'first_name' => 'Central New Jersey',
                'middle_name' => '',
                'last_name' => 'Central New Jersey',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 7,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:08:18',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:08:18',
                'updated_at' => '2020-05-28 22:08:18',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 29,
                'status' => 0,
                'email' => 'admin_central_valley@email.com',
                'user_name' => 'admin_central_valley',
                'password' => '$2y$10$tyrADsDHnpoipO6gcmOC2uRiSSKcdSqwBaFDfIn9nGEovqdhw1Ilu',
                'first_name' => 'Central Valley',
                'middle_name' => '',
                'last_name' => 'Central Valley',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 8,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:08:42',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:08:42',
                'updated_at' => '2020-05-28 22:08:42',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 30,
                'status' => 0,
                'email' => 'admin_dallas_forth_worth@email.com',
                'user_name' => 'admin_dallas_forth_worth',
                'password' => '$2y$10$bblhlG9ExPNtkrqFTKnfEOwFWV58wdz0c4boJIm2.amxsRQerXySG',
                'first_name' => 'Dallas/Forth Worth',
                'middle_name' => '',
                'last_name' => 'Dallas/Forth Worth',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 9,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:09:15',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:09:15',
                'updated_at' => '2020-05-28 22:09:15',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 31,
                'status' => 0,
                'email' => 'admin_dc_metro@email.com',
                'user_name' => 'admin_dc_metro',
                'password' => '$2y$10$.L0h/6kqUdE.o8ih/hb43OBimEX03hlwKWA59Rkcn5/toHFhXGJnm',
                'first_name' => 'DC Metro',
                'middle_name' => '',
                'last_name' => 'DC Metro',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 10,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:09:52',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:09:52',
                'updated_at' => '2020-05-28 22:09:52',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 32,
                'status' => 0,
                'email' => 'admin_greater_birmingham@email.com',
                'user_name' => 'admin_greater_birmingham',
                'password' => '$2y$10$Ln9myfMtd0zDuq2TRUExi.6t9Dp8fC0OMobSRtZkfT1NbvdW0Nobq',
                'first_name' => 'Greater Birmingham',
                'middle_name' => '',
                'last_name' => 'Greater Birmingham',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 11,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:10:23',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:10:23',
                'updated_at' => '2020-05-28 22:10:23',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 33,
                'status' => 0,
                'email' => 'admin_greater_chicago@email.com',
                'user_name' => 'admin_greater_chicago',
                'password' => '$2y$10$Bc67ocbqdtKY1NecbNqFdOavZaZJg.R4.18EoP.tiigx5IExTbX1.',
                'first_name' => 'Greater Chicago',
                'middle_name' => '',
                'last_name' => 'Greater Chicago',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 12,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:10:51',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:10:51',
                'updated_at' => '2020-05-28 22:10:51',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 34,
                'status' => 0,
                'email' => 'admin_greater_denver@email.com',
                'user_name' => 'admin_greater_denver',
                'password' => '$2y$10$JOq9E8e4VFgJGXVRXDJiLOfLTM6DwcljWagolNs8TbRAc4ZeoPExW',
                'first_name' => 'Greater Denver',
                'middle_name' => '',
                'last_name' => 'Greater Denver',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 13,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:11:47',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:11:47',
                'updated_at' => '2020-05-28 22:11:47',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 35,
                'status' => 0,
                'email' => 'admin_greater_east_bay@email.com',
                'user_name' => 'admin_greater_east_bay',
                'password' => '$2y$10$pcJ1GqFzYe3vZ/RBW4DeG.gJGo1o2M8UtofjtnNVeO0hH43i2qJc2',
                'first_name' => 'Greater East Bay',
                'middle_name' => '',
                'last_name' => 'Greater East Bay',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 14,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:12:32',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:12:32',
                'updated_at' => '2020-05-28 22:12:32',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 36,
                'status' => 0,
                'email' => 'admin_greater_jacksonville@email.com',
                'user_name' => 'admin_greater_jacksonville',
                'password' => '$2y$10$JsxP1hFwI5cRLl/q2MQAOOUbdzFdFL0OJzBOVhH2JVdD2BGzAGawy',
                'first_name' => 'Greater Jacksonville',
                'middle_name' => '',
                'last_name' => 'Greater Jacksonville',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 15,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:12:59',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:12:59',
                'updated_at' => '2020-05-28 22:12:59',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 37,
                'status' => 0,
                'email' => 'admin_greater_los_angeles@email.com',
                'user_name' => 'admin_greater_los_angeles',
                'password' => '$2y$10$ylh/adeSYSQAHEvWFHAGV.J5oDf6giwqT4qAWuaFVb/SvIMHLCrV.',
                'first_name' => 'Greater Los Angeles',
                'middle_name' => '',
                'last_name' => 'Greater Los Angeles',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 16,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:13:32',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:13:32',
                'updated_at' => '2020-05-28 22:13:32',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 38,
                'status' => 0,
                'email' => 'admin_greater_miami@email.com',
                'user_name' => 'admin_greater_miami',
                'password' => '$2y$10$zPDMgG0wC0shNW/NloCGmu/ChWkLbi43K0L0IPv9Qh8wzg5YEPilu',
                'first_name' => 'Greater Miami',
                'middle_name' => '',
                'last_name' => 'Greater Miami',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 17,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:13:55',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:13:55',
                'updated_at' => '2020-05-28 22:13:55',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 39,
                'status' => 0,
                'email' => 'admin_greater_orlando@email.com',
                'user_name' => 'admin_greater_orlando',
                'password' => '$2y$10$wsgoht2l/pHQ8hqmbZ8ujeAG5wCgeYEePWXtwdhNub7IVAVQnryTy',
                'first_name' => 'Greater Orlando',
                'middle_name' => '',
                'last_name' => 'Greater Orlando',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 18,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:14:28',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:14:28',
                'updated_at' => '2020-05-28 22:14:28',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 40,
                'status' => 0,
                'email' => 'admin_greater_phoenix@email.com',
                'user_name' => 'admin_greater_phoenix',
                'password' => '$2y$10$GUHjsJxfYzL55MRzPChGyORWs07KvQpWfFlAv.LDBbelCLfdaB5H2',
                'first_name' => 'Greater Phoenix',
                'middle_name' => '',
                'last_name' => 'Greater Phoenix',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 19,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:14:55',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:14:55',
                'updated_at' => '2020-05-28 22:14:55',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 41,
                'status' => 0,
                'email' => 'admin_sacramento@email.com',
                'user_name' => 'admin_sacramento',
                'password' => '$2y$10$50NPmpLVtqe/O7X/aR934.4ws9OAANxQuunQP.6Fu66JKOhcoNIfi',
                'first_name' => 'Greater Sacramento',
                'middle_name' => '',
                'last_name' => 'Greater Sacramento',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 20,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:18:59',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:18:59',
                'updated_at' => '2020-05-28 22:23:13',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 42,
                'status' => 0,
                'email' => 'admin_greater_seattle@email.com',
                'user_name' => 'admin_greater_seattle',
                'password' => '$2y$10$KJGnWVYpZhzRlFG2ZexZL.c9OoWJouJ5phmAdwtxyLFlYkS1MfRsG',
                'first_name' => 'Greater Seattle',
                'middle_name' => '',
                'last_name' => 'Greater Seattle',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 21,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:30:07',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:30:07',
                'updated_at' => '2020-05-28 22:30:07',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 43,
                'status' => 0,
                'email' => 'admin_greater_tampa_bay@email.com',
                'user_name' => 'admin_greater_tampa_bay',
                'password' => '$2y$10$OZRM6Oh1GGqbLokGQDvyAe6RyMiqv2HxsJgLhNtJI5GnvBsSsc4uW',
                'first_name' => 'Greater Tampa Bay',
                'middle_name' => '',
                'last_name' => 'Greater Tampa Bay',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 22,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:33:39',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:33:39',
                'updated_at' => '2020-05-28 22:33:39',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 44,
                'status' => 0,
                'email' => 'admin_greater_toronto@email.com',
                'user_name' => 'admin_greater_toronto',
                'password' => '$2y$10$9eXuHabDU36JAFaNYQR1f.bSx8.Eru2QVyRB5yzAzbUussJmpU9iS',
                'first_name' => 'Greater Toronto',
                'middle_name' => '',
                'last_name' => 'Greater Toronto',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 23,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:34:14',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:34:14',
                'updated_at' => '2020-05-28 22:34:14',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 45,
                'status' => 0,
                'email' => 'admin_houston@email.com',
                'user_name' => 'admin_houston',
                'password' => '$2y$10$49AoP3O.FFiXVU9QKUi71.SN3mftFkXRIFITqdGtvZpJ656iPf20a',
                'first_name' => 'Houston',
                'middle_name' => '',
                'last_name' => 'Houston',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 24,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:34:44',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:34:44',
                'updated_at' => '2020-05-28 22:34:44',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 46,
                'status' => 0,
                'email' => 'admin_inland_empire@email.com',
                'user_name' => 'admin_inland_empire',
                'password' => '$2y$10$gnMqSZeNSufBJ4s367I.Zu56fStdZecQ2bJpTDseKqrDKrFVZdJrq',
                'first_name' => 'Inland Empire',
                'middle_name' => '',
                'last_name' => 'Inland Empire',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 25,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:35:15',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:35:15',
                'updated_at' => '2020-05-28 22:35:15',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 47,
                'status' => 0,
                'email' => 'admin_la_coastal@email.com',
                'user_name' => 'admin_la_coastal',
                'password' => '$2y$10$L5b2nax2bh18A5TkfxV0Wuk9muLiHaARatDwK8P8MvnrVEzeXo8Km',
                'first_name' => 'LA Coastal',
                'middle_name' => '',
                'last_name' => 'LA Coastal',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 26,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:35:47',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:35:47',
                'updated_at' => '2020-05-28 22:35:47',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 48,
                'status' => 0,
                'email' => 'admin_las_vegas@email.com',
                'user_name' => 'admin_las_vegas',
                'password' => '$2y$10$.l3T15XZAYsxmE45W4NEgO8lK.IOcEVoh/D5Z/UbtZIea0K5MsIe2',
                'first_name' => 'Las Vegas',
                'middle_name' => '',
                'last_name' => 'Las Vegas',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 27,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:36:18',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:36:18',
                'updated_at' => '2020-05-28 22:36:18',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 49,
                'status' => 0,
                'email' => 'admin_new_york_east@email.com',
                'user_name' => 'admin_new_york_east',
                'password' => '$2y$10$0llSxtC8OQGtNdiCqPaIpOsGlHXbwKo4cuFHn0GP3Ewm1I1fpKjw.',
                'first_name' => 'New York East',
                'middle_name' => '',
                'last_name' => 'New York East',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 28,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:36:45',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:36:45',
                'updated_at' => '2020-05-28 22:36:45',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 50,
                'status' => 0,
                'email' => 'admin_new_york_manhattan@email.com',
                'user_name' => 'admin_new_york_manhattan',
                'password' => '$2y$10$WTjR7P2r0kBff9dNgQz2MesFX5nyyrNsi7FYJ08XIXYdMgYXh91Le',
                'first_name' => 'New York Manhattan',
                'middle_name' => '',
                'last_name' => 'New York Manhattan',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 29,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:37:12',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:37:12',
                'updated_at' => '2020-05-28 22:37:12',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 51,
                'status' => 0,
                'email' => 'admin_north_los_angeles@email.com',
                'user_name' => 'admin_north_los_angeles',
                'password' => '$2y$10$73Z4kxnoWhLPRlsRMfD4lOklNnSxbERrqIYWH9oTqOQCURyR5bBb.',
                'first_name' => 'North Los Angeles',
                'middle_name' => '',
                'last_name' => 'North Los Angeles',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 30,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:37:42',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:37:42',
                'updated_at' => '2020-05-28 22:37:42',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 52,
                'status' => 0,
                'email' => 'admin_northern_new_jersey@email.com',
                'user_name' => 'admin_northern_new_jersey',
                'password' => '$2y$10$T7CXNCY5.gLGO5uCRBHeN.HTCVGHOpNPmUN9LL5LzmyLpzby9HVIG',
                'first_name' => 'Northern New Jersey',
                'middle_name' => '',
                'last_name' => 'Northern New Jersey',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 31,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:38:10',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:38:10',
                'updated_at' => '2020-05-28 22:38:10',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 53,
                'status' => 0,
                'email' => 'admin_portland@email.com',
                'user_name' => 'admin_portland',
                'password' => '$2y$10$hxw4Aibh4djBQN12sG6VnebuS0a8zinNQ.U4gSMDTclWhJJDR1YQG',
                'first_name' => 'Portland',
                'middle_name' => '',
                'last_name' => 'Portland',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 32,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:38:32',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:38:32',
                'updated_at' => '2020-05-28 22:38:32',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 54,
                'status' => 0,
                'email' => 'admin_san_antonio@email.com',
                'user_name' => 'admin_san_antonio',
                'password' => '$2y$10$cswCk3pwZpORLzsW5d6DvuAUTozfNfgc5yCEs7FHgG5r4ONXS5cAi',
                'first_name' => 'San Antonio',
                'middle_name' => '',
                'last_name' => 'San Antonio',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 33,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:38:56',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:38:56',
                'updated_at' => '2020-05-28 22:38:56',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 55,
                'status' => 0,
                'email' => 'admin_san_diego@email.com',
                'user_name' => 'admin_san_diego',
                'password' => '$2y$10$PVi8coODqNhADf0AD7Kd9ecYKncNbkL8QwgyoiGROa33vUvu.XlR6',
                'first_name' => 'San Diego',
                'middle_name' => '',
                'last_name' => 'San Diego',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 34,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:39:18',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:39:18',
                'updated_at' => '2020-05-28 22:39:18',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 56,
                'status' => 0,
                'email' => 'admin_san_francisco_peninsula@email.com',
                'user_name' => 'admin_san_francisco_peninsula',
                'password' => '$2y$10$FQdxy1iOwENO.6GILTJrgeZ8/OP.WXaDP2ByHvPQWO2z1.UH/qj7S',
                'first_name' => 'San Francisco Peninsula',
                'middle_name' => '',
                'last_name' => 'San Francisco Peninsula',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 35,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:39:48',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:39:48',
                'updated_at' => '2020-05-28 22:39:48',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 57,
                'status' => 0,
                'email' => 'admin_silicon_valley@email.com',
                'user_name' => 'admin_silicon_valley',
                'password' => '$2y$10$Y9sTfiUzgZ5PHFXmYv.CVOc6sIKk6NL/Gf0M1gyhdh5sw5ys3GOcm',
                'first_name' => 'Silicon Valley',
                'middle_name' => '',
                'last_name' => 'Silicon Valley',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 36,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:40:14',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:40:14',
                'updated_at' => '2020-05-28 22:40:14',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 58,
                'status' => 0,
                'email' => 'admin_solano_county@email.com',
                'user_name' => 'admin_solano_county',
                'password' => '$2y$10$CzJRZ1/G0drVL7kvv5I1RO.Xib82LpnLFORVV6tUMrtQ.hhiI8pNu',
                'first_name' => 'Solano County',
                'middle_name' => '',
                'last_name' => 'Solano County',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 37,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:40:37',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:40:37',
                'updated_at' => '2020-05-28 22:40:37',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 59,
                'status' => 0,
                'email' => 'admin_tri_county@email.com',
                'user_name' => 'admin_tri_county',
                'password' => '$2y$10$VPqnNVoJrRE3JISa73cjZOw8IpapXalBwc0PrBlXSQRNUWkDrVcLy',
                'first_name' => 'Tri-County',
                'middle_name' => '',
                'last_name' => 'Tri-County',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 38,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:40:59',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:40:59',
                'updated_at' => '2020-05-28 22:40:59',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 60,
                'status' => 0,
                'email' => 'admin_twin_cities@email.com',
                'user_name' => 'admin_twin_cities',
                'password' => '$2y$10$Of9semrYMDgRBgEVFDdy1OgTz3PjBeDXeBDAvYlZuzlbuvLSumdEq',
                'first_name' => 'Twin Cities',
                'middle_name' => '',
                'last_name' => 'Twin Cities',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 39,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:41:23',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:41:23',
                'updated_at' => '2020-05-28 22:41:23',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 61,
                'status' => 0,
                'email' => 'admin_vancouver@email.com',
                'user_name' => 'admin_vancouver',
                'password' => '$2y$10$1oN1UEw5zGssuLJnjve7Te.LAxWsTLlR558pcdbeM4DpiJu1xT0tO',
                'first_name' => 'Vancouver',
                'middle_name' => '',
                'last_name' => 'Vancouver',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 40,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:41:45',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:41:45',
                'updated_at' => '2020-05-28 22:41:45',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 62,
                'status' => 0,
                'email' => 'admin_ventura_county@email.com',
                'user_name' => 'admin_ventura_county',
                'password' => '$2y$10$jsZfWdEky9Z.7zmaM.jD/.jZIpMB4UwgPqFzzbZ9vA/AoDN27L/y2',
                'first_name' => 'Ventura County',
                'middle_name' => '',
                'last_name' => 'Ventura County',
                'phone' => '',
                'profile_image' => '',
                'chapter_id' => 41,
                'is_active' => 1,
                'last_login' => '2020-05-29 05:42:10',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-28 22:42:10',
                'updated_at' => '2020-05-28 22:42:10',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 63,
                'status' => 0,
                'email' => 'frontend1@dogandrooster.com',
                'user_name' => 'test123',
                'password' => '$2y$10$RT2CEzVY1uFuOMex19ehpOfM51ceQWrmWbmyD6dHdf2ksOyRnPPzK',
                'first_name' => 'Rinnah',
                'middle_name' => '',
                'last_name' => 'Abante',
                'phone' => '123456789',
                'profile_image' => '',
                'chapter_id' => 6,
                'is_active' => 1,
                'last_login' => '2020-05-30 00:53:23',
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2020-05-30 00:00:39',
                'updated_at' => '2020-05-30 00:53:23',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}